Mayhem Integration
mayhemheroes/evm pull request #1
Opened 2022-05-26 01:48 UTC by code-terror

2022-07-24 02:54 UTC, xansec requested changes
Please make the requested changes.

2022-07-24 02:54 UTC, xansec commented on Dockerfile
> +# Build Stage
No need to copy the Mayhemfile inside of the container.

2022-07-24 02:54 UTC, xansec commented on Mayhemfile
> +project: code-terror/evm
Can you make the project name generic?

2022-07-24 03:20 UTC, code-terror commented on Dockerfile
> +# Build Stage
Done!

2022-07-24 03:20 UTC, code-terror commented on Mayhemfile
> +project: code-terror/evm
Done

2022-07-24 03:21 UTC, code-terror commented
@xansec ...pushed the changes.

2022-07-25 19:05 UTC, xansec approved these changes
LGTM!

2022-07-25 19:05 UTC, merged